spring:
  freemarker:
    template-loader-path: classpath:/templates/
    prefer-file-system-access: false


server:
  port: 8761
  name: SERVICE-REGISTRY


  zipkin:
    base-url: http://localhost:9411

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
